stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node
      shellScript: |-
            npm install --registry=https://registry.npm.taobao.org
            npm run build:prod
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ui:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml