stages:
- name: Build
  steps:
  - runScriptConfig:
      image: kkarczmarczyk/node-yarn:latest
      shellScript: |-
            yarn install
            yarn run build:prod
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ui:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml