# 负载均衡
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: api
spec:
  rules:
  - host: xip.io
    http:
      paths:
        - backend:
            serviceName: ui-service
            servicePort: http
        - backend:
            serviceName: micro
            servicePort: micro-http
          path: /rpc
---
kind: Service
apiVersion: v1
metadata:
  name: ui-service
  namespace: api
spec:
  selector:
    app: ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: api
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: ui
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
